FROM python:3

EXPOSE 8000

ENV HOME=/code
RUN mkdir -p ${HOME}
WORKDIR ${HOME}

ADD requirements.txt app.py ${HOME}/

RUN pip install -r requirements.txt

CMD ["python3", "-m", "flask", "run", "--host", "0.0.0.0"]
